GET https://localhost:4300/api/compromissos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDc4NDYyNi1mOTBlLTRlZDctYjk2YS0wOGRjZjJiYjEwNjAiLCJlbWFpbCI6InRlc3RlQHRlc3RlIiwidW5pcXVlX25hbWUiOiJ0ZXN0ZSIsImdpdmVuX25hbWUiOiJ0ZXN0ZSB0ZXN0ZSIsIm5iZiI6MTcyOTc3Njk5OSwiZXhwIjoxNzMwMjA4OTk5LCJpYXQiOjE3Mjk3NzY5OTksImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.y9zFDkH2Muyw7BLEIjUdZLiypvPNjEhip-waCOt2hNY