GET https://localhost:4300/api/contatos
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDc4NDYyNi1mOTBlLTRlZDctYjk2YS0wOGRjZjJiYjEwNjAiLCJlbWFpbCI6InRlc3RlQHRlc3RlIiwidW5pcXVlX25hbWUiOiJ0ZXN0ZSIsImdpdmVuX25hbWUiOiJ0ZXN0ZSB0ZXN0ZSIsIm5iZiI6MTcyOTcwNDUwMSwiZXhwIjoxNzMwMTM2NTAxLCJpYXQiOjE3Mjk3MDQ1MDEsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.K1SqwbjWwzUTsIT3SyOwjtN4YEtArI2NvhHwMYZbr3E